### What this notebook does
1. Downloads KDDTrain+.txt and KDDTest+.txt from GitHub
3. Creates "labeled_dataset.csv"

## Imports

In [20]:
import os
import requests
import numpy as np
import pandas as pd

%matplotlib inline
print("Libraries imported")

Libraries imported

## All Files Path and Locations

In [21]:
# The Path in which Data is Stored
DATA_DIR = "data"
os.makedirs(DATA_DIR, exist_ok=True)

# The URL for Dataset
URLS = {
    "KDDTrain+.txt": "https://raw.githubusercontent.com/defcom17/NSL_KDD/master/KDDTrain+.txt",
    "KDDTest+.txt":  "https://raw.githubusercontent.com/defcom17/NSL_KDD/master/KDDTest+.txt",
}

# All Columns are Labeled
COLUMNS = [
    "duration", "protocol_type", "service", "flag",
    "src_bytes", "dst_bytes", "land", "wrong_fragment", "urgent", "hot",
    "num_failed_logins", "logged_in", "num_compromised", "root_shell",
    "su_attempted", "num_root", "num_file_creations", "num_shells",
    "num_access_files", "num_outbound_cmds", "is_host_login", "is_guest_login",
    "count", "srv_count", "serror_rate", "srv_serror_rate", "rerror_rate",
    "srv_rerror_rate", "same_srv_rate", "diff_srv_rate", "srv_diff_host_rate",
    "dst_host_count", "dst_host_srv_count", "dst_host_same_srv_rate",
    "dst_host_diff_srv_rate", "dst_host_same_src_port_rate",
    "dst_host_srv_diff_host_rate", "dst_host_serror_rate",
    "dst_host_srv_serror_rate", "dst_host_rerror_rate",
    "dst_host_srv_rerror_rate", "class", "difficulty_level"
]

print(f"Total columns : {len(COLUMNS)}")

Total columns : 43

## Downlaad Data without any Error

In [19]:
def download_file(url, filename):
    path = os.path.join("..", DATA_DIR, filename)
    if os.path.exists(path):
        print(f"{filename} already exists")
        return
    print(f"Downloading {filename}")
    try:
        response = requests.get(url, stream=True)
        response.raise_for_status()
        with open(path, "wb") as f:
            
            # It is chunked to avoid downloading everything as a whole
            for chunk in response.iter_content(chunk_size=8192):
                f.write(chunk)
        print(f"Saved to {path}")
    except Exception as e:
        print(f"Failed to download {filename}: {e}")


print("Downloading dataset files: ")
for filename, url in URLS.items():
    download_file(url, filename)
print("\nAll files should now be in 'data' folder")

Downloading dataset files:
Downloading KDDTrain+.txt …
Failed to download KDDTrain+.txt: [Errno 2] No such file or directory: '..\\data\\KDDTrain+.txt'
Downloading KDDTest+.txt …
Failed to download KDDTest+.txt: [Errno 2] No such file or directory: '..\\data\\KDDTest+.txt'

All files should now be in 'data' folder

## Load and Label the Dataset

In [25]:
# Assigning Path for Train and Test Data
train_path = os.path.join(DATA_DIR, "KDDTrain+.txt")
test_path  = os.path.join(DATA_DIR, "KDDTest+.txt")

# Assigning Variables for Train and Test Data
train_df = pd.read_csv(train_path, header=None, names=COLUMNS)
test_df  = pd.read_csv(test_path,  header=None, names=COLUMNS)

print(f"Training set : {train_df.shape[0]:}")
print(f"Test set     : {test_df.shape[0]:}")

Training set : 125973
Test set     : 22544

## First 5 Rows

In [24]:
print("First 5 Rows")
train_df.head()

First 5 Rows

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,class,difficulty_level
0,0,tcp,ftp_data,SF,491,0,0,0,0,0,...,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,normal,20
1,0,udp,other,SF,146,0,0,0,0,0,...,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal,15
2,0,tcp,private,S0,0,0,0,0,0,0,...,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,neptune,19
3,0,tcp,http,SF,232,8153,0,0,0,0,...,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal,21
4,0,tcp,http,SF,199,420,0,0,0,0,...,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal,21

## Basic Details

In [26]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125973 entries, 0 to 125972
Data columns (total 43 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   duration                     125973 non-null  int64
 1   protocol_type                125973 non-null  object
 2   service                      125973 non-null  object
 3   flag                         125973 non-null  object
 4   src_bytes                    125973 non-null  int64
 5   dst_bytes                    125973 non-null  int64
 6   land                         125973 non-null  int64
 7   wrong_fragment               125973 non-null  int64
 8   urgent                       125973 non-null  int64
 9   hot                          125973 non-null  int64
 10  num_failed_logins            125973 non-null  int64
 11  logged_in                    125973 non-null  int64
 12  num_compromised              125973 non-null  int64
 13  root_shell                   125973 non-null  int64
 14  su_attempted                 125973 non-null  int64
 15  num_root                     125973 non-null  int64
 16  num_file_creations           125973 non-null  int64
 17  num_shells                   125973 non-null  int64
 18  num_access_files             125973 non-null  int64
 19  num_outbound_cmds            125973 non-null  int64
 20  is_host_login                125973 non-null  int64
 21  is_guest_login               125973 non-null  int64
 22  count                        125973 non-null  int64
 23  srv_count                    125973 non-null  int64
 24  serror_rate                  125973 non-null  float64
 25  srv_serror_rate              125973 non-null  float64
 26  rerror_rate                  125973 non-null  float64
 27  srv_rerror_rate              125973 non-null  float64
 28  same_srv_rate                125973 non-null  float64
 29  diff_srv_rate                125973 non-null  float64
 30  srv_diff_host_rate           125973 non-null  float64
 31  dst_host_count               125973 non-null  int64
 32  dst_host_srv_count           125973 non-null  int64
 33  dst_host_same_srv_rate       125973 non-null  float64
 34  dst_host_diff_srv_rate       125973 non-null  float64
 35  dst_host_same_src_port_rate  125973 non-null  float64
 36  dst_host_srv_diff_host_rate  125973 non-null  float64
 37  dst_host_serror_rate         125973 non-null  float64
 38  dst_host_srv_serror_rate     125973 non-null  float64
 39  dst_host_rerror_rate         125973 non-null  float64
 40  dst_host_srv_rerror_rate     125973 non-null  float64
 41  class                        125973 non-null  object
 42  difficulty_level             125973 non-null  int64
dtypes: float64(15), int64(24), object(4)
memory usage: 41.3+ MB

In [27]:
train_df.describe()

,duration,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,num_compromised,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,difficulty_level
count,125973.00000,1.259730e+05,1.259730e+05,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,...,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000
mean,287.14465,4.556674e+04,1.977911e+04,0.000198,0.022687,0.000111,0.204409,0.001222,0.395736,0.279250,...,115.653005,0.521242,0.082951,0.148379,0.032542,0.284452,0.278485,0.118832,0.120240,19.504060
std,2604.51531,5.870331e+06,4.021269e+06,0.014086,0.253530,0.014366,2.149968,0.045239,0.489010,23.942042,...,110.702741,0.448949,0.188922,0.308997,0.112564,0.444784,0.445669,0.306557,0.319459,2.291503
min,0.00000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.00000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,10.000000,0.050000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,18.000000
50%,0.00000,4.400000e+01,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,63.000000,0.510000,0.020000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,20.000000
75%,0.00000,2.760000e+02,5.160000e+02,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,...,255.000000,1.000000,0.070000,0.060000,0.020000,1.000000,1.000000,0.000000,0.000000,21.000000
max,42908.00000,1.379964e+09,1.309937e+09,1.000000,3.000000,3.000000,77.000000,5.000000,1.000000,7479.000000,...,255.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,21.000000

In [29]:
print("Missing Values:")
missing = train_df.isnull().sum()
print(missing[missing > 0] if missing.any() else "No missing values found")

Missing Values:
No missing values found

In [35]:
print("Different Class Distribution")
class_counts = train_df["class"].value_counts()
print(class_counts)
print(f"\nTotal unique classes : {class_counts.shape[0]}")

Different Class Distribution
class
normal             67343
neptune            41214
satan               3633
ipsweep             3599
portsweep           2931
smurf               2646
nmap                1493
back                 956
teardrop             892
warezclient          890
pod                  201
guess_passwd          53
buffer_overflow       30
warezmaster           20
land                  18
imap                  11
rootkit               10
loadmodule             9
ftp_write              8
multihop               7
phf                    4
perl                   3
spy                    2
Name: count, dtype: int64

Total unique classes : 23

## Save Labeled Dataset For Easy Access

In [38]:
labeled_path = os.path.join(DATA_DIR, "labeled_dataset.csv")
train_df.to_csv(labeled_path, index=False)
print(f"Labeled dataset saved: {labeled_path}")
print(f"{train_df.shape}")

Labeled dataset saved: data\labeled_dataset.csv
(125973, 43)

## 6. Train vs Test Set Comparison

Verify the test set has a representative sample of attack types seen in training.

In [10]:
# Side-by-side class distribution: train vs test
train_dist = train_df['class'].value_counts(normalize=True).rename('Train %')
test_dist  = test_df['class'].value_counts(normalize=True).rename('Test %')
comparison = pd.concat([train_dist, test_dist], axis=1).fillna(0).mul(100).round(2)

print('Class Distribution — Train vs Test (%):')
print(comparison.sort_values('Train %', ascending=False).to_string())

Class Distribution — Train vs Test (%):
                 Train %  Test %
class
normal             53.46   43.08
neptune            32.72   20.66
satan               2.88    3.26
ipsweep             2.86    0.63
portsweep           2.33    0.70
smurf               2.10    2.95
nmap                1.19    0.32
back                0.76    1.59
teardrop            0.71    0.05
warezclient         0.71    0.00
pod                 0.16    0.18
guess_passwd        0.04    5.46
buffer_overflow     0.02    0.09
warezmaster         0.02    4.19
land                0.01    0.03
imap                0.01    0.00
rootkit             0.01    0.06
loadmodule          0.01    0.01
ftp_write           0.01    0.01
multihop            0.01    0.08
phf                 0.00    0.01
perl                0.00    0.01
spy                 0.00    0.00
mscan               0.00    4.42
apache2             0.00    3.27
processtable        0.00    3.04
snmpguess           0.00    1.47
saint               0.00    1.42
mailbomb            0.00    1.30
snmpgetattack       0.00    0.79
httptunnel          0.00    0.59
named               0.00    0.08
ps                  0.00    0.07
sendmail            0.00    0.06
xterm               0.00    0.06
xlock               0.00    0.04
xsnoop              0.00    0.02
worm                0.00    0.01
sqlattack           0.00    0.01
udpstorm            0.00    0.01

## 7. Column Reference

| Column | Description |
|--------|-------------|
| `duration` | Connection length in seconds |
| `protocol_type` | Protocol used: `tcp`, `udp`, `icmp` |
| `service` | Network service at destination (e.g. `http`, `ftp`) |
| `flag` | Connection status (e.g. `SF` = normal, `S0` = no reply) |
| `src_bytes` | Bytes sent from source to destination |
| `dst_bytes` | Bytes sent from destination back to source |
| `land` | 1 if source and destination IP/port are the same (Land DoS) |
| `wrong_fragment` | Number of malformed packet fragments |
| `urgent` | Packets with urgent bit set |
| `hot` | Number of "hot" indicators (e.g. accessing root directories) |
| `num_failed_logins` | Failed login attempts |
| `logged_in` | 1 if user successfully logged in |
| `num_compromised` | Conditions indicating system compromise |
| `root_shell` | 1 if root shell was obtained |
| `su_attempted` | 1 if `su` to root was attempted |
| `num_root` | Root accesses performed |
| `num_file_creations` | File creation operations |
| `num_shells` | Shell prompts generated |
| `num_access_files` | Attempts to access critical files (e.g. `/etc/passwd`) |
| `num_outbound_cmds` | Outbound commands in FTP session |
| `is_host_login` | 1 if login belongs to host admin list |
| `is_guest_login` | 1 if login is a guest login |
| `count` | Connections to same host in past 2 seconds |
| `srv_count` | Connections to same service in past 2 seconds |
| `serror_rate` | % connections with SYN errors (same host) |
| `srv_serror_rate` | % connections with SYN errors (same service) |
| `rerror_rate` | % connections with REJ errors (same host) |
| `srv_rerror_rate` | % connections with REJ errors (same service) |
| `same_srv_rate` | % connections to same host → same service |
| `diff_srv_rate` | % connections to same host → different service |
| `srv_diff_host_rate` | % connections to same service from different hosts |
| `dst_host_count` | Connections to same destination host (last 100) |
| `dst_host_srv_count` | Connections to same host + service (last 100) |
| `dst_host_same_srv_rate` | % connections to same service |
| `dst_host_diff_srv_rate` | % connections to different services |
| `dst_host_same_src_port_rate` | % connections from same source port |
| `dst_host_srv_diff_host_rate` | % connections to same service from different hosts |
| `dst_host_serror_rate` | % SYN errors to this destination host |
| `dst_host_srv_serror_rate` | % SYN errors to this host + service |
| `dst_host_rerror_rate` | % REJ errors to this destination host |
| `dst_host_srv_rerror_rate` | % REJ errors to this host + service |
| `class` | **Target variable** — `normal` or attack name |
| `difficulty_level` | Classification difficulty score (0–21) |

---
## Here Output Files are created and Labeled properly then saved

**Output files created:**
- `data/KDDTrain+.txt` — raw training data
- `data/KDDTest+.txt`  — raw test data
- `data/labeled_dataset.csv` — cleaned, labeled training set
- The Data is clean without any missing values
- Instalation was completed without any issues